### ISSUE TITLE
Notification System und anderes

### ISSUE THREAD

**Issue by xVoiceSyntax** [N2nd/Horizon#1]
EN: Why are you using the Notification System from superblaubeere27. And please rename Generics to a upper case "name" and add "Exception" Classes as suffix to your exception classes.

DE: Warum Sie das Benachrichtigungssystem von superblaubeere27 verwenden. Und bitte benennen Sie Generics in einen großgeschriebenen "Namen" um und fügen Sie "Exception" als Suffix zu Ihren "Exception" Klassen hinzu.

**Comment by LNonymous** [comment]
Ich benutze das Benachrichtigungssystem von superblaubeere27 weil ich es gut finde :)

**Comment by LNonymous** [comment]
Thx
